{
 "title": "esgyn_db",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Node", "query": "tag_values(redis_uptime,host)" }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "max",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "proc.stat.cpu_percent"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "zimsum",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "proc.stat.cpu_percent"
      }
     ]
    },
    {
     "title": "Memory-Free",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "max",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "currentFilterKey": "host",
       "currentFilterType": "literal_or",
       "currentFilterValue": "$Node",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "proc.meminfo.free_percent",
       "metrics": [
        {
         "field": "system.memory.used.pct",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "beat.hostname:$Node",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory-Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "counterResetValue": "0",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "proc.meminfo.free_percent"
      }
     ]
    },
    {
     "title": "Hdfs_size",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "sum",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "esgyn.data.size"
      }
     ]
    },
    {
     "title": "Instantaneous /perSec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "metric": "esgyn.data.size"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HBase_Status",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.hbase.running" }
     ]
    },
    {
     "title": "HBase_Regionserver",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.hbase.regionserver" }
     ]
    },
    {
     "title": "UP_Nodes",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.nodes.up" }
     ]
    },
    {
     "title": "DOWN_Nodes",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.nodes.down" }
     ]
    }
   ]
  },
  {
   "title": "Trafodion-Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DTM_Configure",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.configure" }
     ]
    },
    {
     "title": "DTM_Actual",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.running" }
     ]
    },
    {
     "title": "DTM_Down",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.down" }
     ]
    },
    {
     "title": "RMS_Configure",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.rms.configure" }
     ]
    },
    {
     "title": "RMS_Actual",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.running" }
     ]
    },
    {
     "title": "RMS_Down",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.rms.down" }
     ]
    },
    {
     "title": "DcsMaster_Configure",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.configure" }
     ]
    },
    {
     "title": "DcsMaster_Actual",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.running" }
     ]
    },
    {
     "title": "DcsMaster_Down",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.down" }
     ]
    },
    {
     "title": "DcsServer_Configure",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.configure" }
     ]
    },
    {
     "title": "DcsServer_Actual",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.running" }
     ]
    },
    {
     "title": "DcsServer_Down",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.down" }
     ]
    },
    {
     "title": "mxosrvr_Configure",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.configure" }
     ]
    },
    {
     "title": "mxosrvr_Actual",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.running" }
     ]
    },
    {
     "title": "mxosrvr_Down",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.down" }
     ]
    }
   ]
  }
 ]
}