{
 "title": "esgyn_db",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "proc.stat.cpu_percent"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "proc.stat.cpu_percent"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "currentFilterKey": "host",
     "currentFilterType": "literal_or",
     "currentFilterValue": "$Node",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "proc.meminfo.free_percent",
     "metrics": [
      {
       "field": "system.memory.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "beat.hostname:$Node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "counterResetValue": "0",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "proc.meminfo.free_percent"
    }
   ]
  },
  {
   "title": "Esgyndb Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyndb.memory.usage"
    }
   ]
  },
  {
   "title": "Esgyndb Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyndb.memory.usage"
    }
   ]
  },
  {
   "title": "Mxosrvr Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 7 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyndb.mxosrvr.memory"
    }
   ]
  },
  {
   "title": "Monitor Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 7 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyndb.monitor.memory"
    }
   ]
  },
  {
   "title": "Tm Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 7 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyndb.tm.memory"
    }
   ]
  },
  {
   "title": "STFS Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyn.stfs.percent"
    }
   ]
  },
  {
   "title": "STFS Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyn.stfs.percent"
    }
   ]
  },
  {
   "title": "Schema Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 14 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyn.schema.size"
    }
   ]
  },
  {
   "title": "Schema Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyn.schema.size"
    }
   ]
  },
  {
   "title": "STFS Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "aggregator": "min", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.stfs.running" }
   ]
  },
  {
   "title": "HBase Regionserver",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "aggregator": "min", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.hbase.regionserver" }
   ]
  },
  {
   "title": "HBase Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "aggregator": "min", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.hbase.running" }
   ]
  },
  {
   "title": "UP Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.nodes.up" }
   ]
  },
  {
   "title": "DOWN Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyn.nodes.down" }
   ]
  },
  {
   "title": "Hdfs Size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 21 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "esgyn.data.size"
    }
   ]
  },
  {
   "title": "Trafodion-Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "DTM Configure",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.configure" }
     ]
    },
    {
     "title": "DTM Actual",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.running" }
     ]
    },
    {
     "title": "DTM Down",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dtm.down" }
     ]
    },
    {
     "title": "RMS Configure",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.rms.configure" }
     ]
    },
    {
     "title": "RMS Actual",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.rms.running" }
     ]
    },
    {
     "title": "RMS Down",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.rms.down" }
     ]
    },
    {
     "title": "DcsMaster Configure",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.configure" }
     ]
    },
    {
     "title": "DcsMaster Actual",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.running" }
     ]
    },
    {
     "title": "DcsMaster Down",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsmaster.down" }
     ]
    },
    {
     "title": "DcsServer Configure",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.configure" }
     ]
    },
    {
     "title": "DcsServer Actual",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.running" }
     ]
    },
    {
     "title": "DcsServer Down",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.dcsserver.down" }
     ]
    },
    {
     "title": "Mxosrvr Configure",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.configure" }
     ]
    },
    {
     "title": "Mxosrvr Actual",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.running" }
     ]
    },
    {
     "title": "Mxosrvr Down",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "esgyndb.mxosrvr.down" }
     ]
    }
   ]
  }
 ]
}